name: todo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.2.2
  get: ^4.6.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  adaptive_action_sheet: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  test: ^1.25.8
  mockito: ^5.4.4
  build_runner: ^2.4.13
  integration_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  generate: true