name: flutter_todo
description: "A todo app powered by flutter"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.5.0-180.3.beta <4.0.0"
dev_dependencies:
  melos: ^6.2.0
