name: flutter_todo
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  get: ^4.6.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  adaptive_action_sheet: ^2.0.3
  calendar_plugin:
    git:
      url: https://github.com/futurechallenger/calendar_plugin.git
      ref: main
  intl: any
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.9
  integration_test:
    sdk: flutter
  freezed: ^2.5.1
  json_serializable: ^6.7.1
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
